replicaCount: 1

imagePullSecrets:
  - name: fe-regcred

v1_image:
  repository: gracehpark/foodteacher-fe
  pullPolicy: IfNotPresent
  tag: "b9f6ce8166a78e9eba5a6e147d9a08f881dfebd4"

v2_image:
  repository: gracehpark/foodteacher-fe-2
  pullPolicy: IfNotPresent
  tag: "06ddc94"

dev_image:
  repository: gracehpark/foodteacher-fe-dev
  pullPolicy: IfNotPresent
  tag: "8ea9b3a"


imageCredentials:
  registry: gracehpark
  username: gracehpark
  password: 9Nvkh96heuct~!
  email: gracehpark@naver.com

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

service:
  list:
    - name: fe
      type: NodePort  
      port: 80
      targetport: 3000
    - name: fe-2
      type: NodePort
      port: 80
      targetport: 3000
    - name: fe-dev
      type: NodePort
      port: 80
      targetport: 3000
      

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
