apiVersion: v1
kind: ConfigMap
metadata:
  namespace: efk
  name: elasticsearch-config
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    cluster.name: minikube	# 클러스터 이름
    network.host: 0.0.0.0
