apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe
  name: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      imagePullSecrets:
      - name: fe-regcred
      containers:
      - image: "{{ .Values.v1_image.repository }}:{{ .Values.v1_image.tag }}"
        name: fe
        ports: # 컨테이너가 개방할 포트 정의. 정의 안하면 자동 할당
        - containerPort: 3000
