# templates/mysql-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
data:
  my.cnf: |
    [mysqld]
    max_connections = 600
    read_buffer_size = 1048576
    net_read_timeout = 360
    net_write_timeout = 360
    skip-external-locking
    skip-host-cache
    skip-name-resolve
    [mysql]
    bind-address = 0.0.0.0
---
# templates/redis-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
data:
  redis.conf: |
    maxmemory 20mb
    maxmemory-policy allkeys-lru
