{{- range .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ .app }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  type: {{ .type }}

---
{{- end }}

